apiVersion: v1
kind: Service
metadata:
  name: dotnet-guestbook-grafana
  labels:
    app: dotnet-guestbook
    tier: graphana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: dotnet-guestbook
    tier: graphana