kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet-guestbook-mongodb
  labels:
    app: dotnet-guestbook
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-guestbook
      tier: db
  template:
    metadata:
      labels:
        app: dotnet-guestbook
        tier: db
    spec:
      containers:
        - name: mongo
          image: mongo:4
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: pv-mongodb
              subPath: mongodb
      volumes:
      - name: pv-mongodb
        persistentVolumeClaim:
          claimName: guestbook-persistent-volume-claim