kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet-guestbook-grafana
  labels:
    app: dotnet-guestbook
    tier: graphana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-guestbook
      tier: graphana
  template:
    metadata:
      labels:
        app: dotnet-guestbook
        tier: graphana
    spec:
      containers:
        - name: grafana
          image: dotnet-guestbook-grafana
          ports:
            - name: grafana-rpc
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: bitnami
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: pv-grafana
              subPath: storage
      volumes:
      - name: pv-grafana
        persistentVolumeClaim:
          claimName: grafana-persistent-volume-claim