apiVersion: v1
kind: Service
metadata:
  name: dotnet-guestbook-loki
  labels:
    app: dotnet-guestbook
    tier: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
      name: http
    - port: 9096
      targetPort: 9096
      name: grpc
  selector:
    app: dotnet-guestbook
    tier: loki