apiVersion: v1
kind: Service
metadata:
  name: dotnet-guestbook-loki
  labels:
    app: dotnet-guestbook
    tier: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: dotnet-guestbook
    tier: loki