apiVersion: v1
kind: Service
metadata:
  name: dotnet-guestbook-prometheus
  labels:
    app: dotnet-guestbook
    tier: prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: dotnet-guestbook
    tier: prometheus