kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet-guestbook-prometheus
  labels:
    app: dotnet-guestbook
    tier: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-guestbook
      tier: prometheus
  template:
    metadata:
      labels:
        app: dotnet-guestbook
        tier: prometheus
    spec:
      containers:
        - name: prometheus
          image: dotnet-guestbook-prometheus
          volumeMounts:
            - mountPath: /prometheus
              name: pv-prometheus
              subPath: storage
            - mountPath: /etc/prometheus
              name: pv-prometheus
              subPath: config
      volumes:
      - name: pv-prometheus
        persistentVolumeClaim:
          claimName: prometheus-persistent-volume-claim