apiVersion: v1
kind: PersistentVolume
metadata:
  name: guestbook-persistent-volume
spec:
  storageClassName: guestbook-storageclass
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/nicholasnewdigate/Development/guestbook-dotnet6/persistence