apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistent-volume
spec:
  storageClassName: prometheus-storageclass
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/nicholasnewdigate/Development/guestbook-dotnet6/persistence/prometheus