apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: prometheus-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain