apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: grafana-storageclass